### PR TITLE
Clean up and prep for Python 3

### PR DESCRIPTION
**Pull request by ThrawnCA**
- Fix Flake8 errors
- Use 'six' module to improve Python 3 compatibility, #35

### CODE REVIEW

**Review by markstuart — APPROVED** [review]
Looks good to me @ThrawnCA, are you aware of anything else that will need attention for Python 3 compatibility?

**Comment by ThrawnCA** [comment]
> Looks good to me @ThrawnCA, are you aware of anything else that will need attention for Python 3 compatibility?

Not that I'm aware of. I can't make any promises about CKAN 2.9, but Flake8 under Python 3 was happy with this, so the syntax is probably okay on that front.

**Comment by ThrawnCA** [comment]
@markstuart I've done some work this week on adapting our CSRF filter to Flask. That's something that will need to happen on a larger scale for ckan 2.9; everything in `controllers.py` will need to be converted to blueprints.

On the bright side of things, Flask provides better hooks, making the middleware patch unnecessary.

**Comment by ThrawnCA** [comment]
@markstuart NB I can't merge this myself.

**Pull request merged**
